# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-11 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 0, 22, 881864, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 0, 22, 876012, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 0, 22, 880606, tzinfo=utc), verbose_name='date published'),
        ),
    ]
