# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-11 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question_game', '0003_auto_20181011_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='needs_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 4, 32, 793038, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 4, 32, 787118, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 4, 32, 791759, tzinfo=utc), verbose_name='date published'),
        ),
    ]
